package co.kr.snaptime.ui.Icon.homeicon

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.graphics.PathFillType.Companion.NonZero
import androidx.compose.ui.graphics.SolidColor
import androidx.compose.ui.graphics.StrokeCap.Companion.Butt
import androidx.compose.ui.graphics.StrokeJoin.Companion.Miter
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.ImageVector.Builder
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp
import co.kr.snaptime.ui.Icon.HomeIcon

public val HomeIcon.Qrcodeicon: ImageVector
    get() {
        if (_qrcodeicon != null) {
            return _qrcodeicon!!
        }
        _qrcodeicon = Builder(name = "Qrcodeicon", defaultWidth = 30.0.dp, defaultHeight = 30.0.dp,
                viewportWidth = 30.0f, viewportHeight = 30.0f).apply {
            path(fill = SolidColor(Color(0xFFA4CEFF)), stroke = null, strokeLineWidth = 0.0f,
                    strokeLineCap = Butt, strokeLineJoin = Miter, strokeLineMiter = 4.0f,
                    pathFillType = NonZero) {
                moveTo(18.75f, 26.25f)
                horizontalLineTo(16.25f)
                verticalLineTo(23.75f)
                horizontalLineTo(18.75f)
                verticalLineTo(26.25f)
                close()
                moveTo(16.25f, 17.5f)
                horizontalLineTo(13.75f)
                verticalLineTo(23.75f)
                horizontalLineTo(16.25f)
                verticalLineTo(17.5f)
                close()
                moveTo(26.25f, 15.0f)
                horizontalLineTo(23.75f)
                verticalLineTo(20.0f)
                horizontalLineTo(26.25f)
                verticalLineTo(15.0f)
                close()
                moveTo(23.75f, 12.5f)
                horizontalLineTo(21.25f)
                verticalLineTo(15.0f)
                horizontalLineTo(23.75f)
                verticalLineTo(12.5f)
                close()
                moveTo(8.75f, 15.0f)
                horizontalLineTo(6.25f)
                verticalLineTo(17.5f)
                horizontalLineTo(8.75f)
                verticalLineTo(15.0f)
                close()
                moveTo(6.25f, 12.5f)
                horizontalLineTo(3.75f)
                verticalLineTo(15.0f)
                horizontalLineTo(6.25f)
                verticalLineTo(12.5f)
                close()
                moveTo(15.0f, 6.25f)
                horizontalLineTo(17.5f)
                verticalLineTo(3.75f)
                horizontalLineTo(15.0f)
                verticalLineTo(6.25f)
                close()
                moveTo(5.625f, 5.625f)
                verticalLineTo(9.375f)
                horizontalLineTo(9.375f)
                verticalLineTo(5.625f)
                horizontalLineTo(5.625f)
                close()
                moveTo(11.25f, 11.25f)
                horizontalLineTo(3.75f)
                verticalLineTo(3.75f)
                horizontalLineTo(11.25f)
                verticalLineTo(11.25f)
                close()
                moveTo(5.625f, 20.625f)
                verticalLineTo(24.375f)
                horizontalLineTo(9.375f)
                verticalLineTo(20.625f)
                horizontalLineTo(5.625f)
                close()
                moveTo(11.25f, 26.25f)
                horizontalLineTo(3.75f)
                verticalLineTo(18.75f)
                horizontalLineTo(11.25f)
                verticalLineTo(26.25f)
                close()
                moveTo(20.625f, 5.625f)
                verticalLineTo(9.375f)
                horizontalLineTo(24.375f)
                verticalLineTo(5.625f)
                horizontalLineTo(20.625f)
                close()
                moveTo(26.25f, 11.25f)
                horizontalLineTo(18.75f)
                verticalLineTo(3.75f)
                horizontalLineTo(26.25f)
                verticalLineTo(11.25f)
                close()
                moveTo(23.75f, 23.75f)
                verticalLineTo(20.0f)
                horizontalLineTo(18.75f)
                verticalLineTo(22.5f)
                horizontalLineTo(21.25f)
                verticalLineTo(26.25f)
                horizontalLineTo(26.25f)
                verticalLineTo(23.75f)
                horizontalLineTo(23.75f)
                close()
                moveTo(21.25f, 15.0f)
                horizontalLineTo(16.25f)
                verticalLineTo(17.5f)
                horizontalLineTo(21.25f)
                verticalLineTo(15.0f)
                close()
                moveTo(16.25f, 12.5f)
                horizontalLineTo(8.75f)
                verticalLineTo(15.0f)
                horizontalLineTo(11.25f)
                verticalLineTo(17.5f)
                horizontalLineTo(13.75f)
                verticalLineTo(15.0f)
                horizontalLineTo(16.25f)
                verticalLineTo(12.5f)
                close()
                moveTo(17.5f, 11.25f)
                verticalLineTo(8.75f)
                horizontalLineTo(15.0f)
                verticalLineTo(6.25f)
                horizontalLineTo(12.5f)
                verticalLineTo(11.25f)
                horizontalLineTo(17.5f)
                close()
                moveTo(8.4375f, 6.5625f)
                horizontalLineTo(6.5625f)
                verticalLineTo(8.4375f)
                horizontalLineTo(8.4375f)
                verticalLineTo(6.5625f)
                close()
                moveTo(8.4375f, 21.5625f)
                horizontalLineTo(6.5625f)
                verticalLineTo(23.4375f)
                horizontalLineTo(8.4375f)
                verticalLineTo(21.5625f)
                close()
                moveTo(23.4375f, 6.5625f)
                horizontalLineTo(21.5625f)
                verticalLineTo(8.4375f)
                horizontalLineTo(23.4375f)
                verticalLineTo(6.5625f)
                close()
            }
        }
        .build()
        return _qrcodeicon!!
    }

private var _qrcodeicon: ImageVector? = null
